version: '3'

services:

    app:
        build: .
        container_name: mediaw-app
        volumes:
            - .:/var/www
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - app-network
        depends_on:
            - db

    nginx:
        build: docker/nginx
        container_name: mediaw-nginx
        restart: always
        tty: true
        ports:
            - "80:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./docker/mysql
        container_name: mediaw-db
        restart: always
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./docker/dbdata:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=mediaw_db
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - app-network

networks:
    app-network:
        driver: bridge